version: '2'
services:
  front_service:
    image: eventos/eventos-front:latest
    expose:
      - 80
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - network
    volumes:
      - front_dist:/usr/share/nginx/html
      - front_logs:/var/log
    restart: always
  proxy_service:
    image:  colsubsidioproxy/front-proxy:latest
    ports:
      - 80:80
    build:
     context: ../proxys/front-proxy
     dockerfile: ./Dockerfile
    networks:
      - network 
    volumes:
      - proxy_config:/etc/nginx
      - proxy_logs:/var/log 
    restart: always 
    depends_on:
      - front_service              
volumes:
  front_dist:
  front_logs:
  proxy_config:
  proxy_logs:
networks:
  network: