version: '2'
services:
 front_service:
    image:  crishubprojects/eventos-front:latest
    expose:
      - "80"
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - network
    volumes:
      - front-dist:/usr/share/nginx/html/eventos
      - front-logs:/var/log
    restart: always
 proxy_service:
    image:  crishubprojects/eventos-front-proxy:latest
    ports:
      - "80:80"
    build:
     context: ./
     dockerfile: ./Dockerfile
    networks:
      - network
    volumes:
      - "proxy-config:/etc/nginx"
      - proxy-logs:/var/log
    restart: always
volumes:
  front-dist:
  front-logs:
  proxy-config:
  proxy-logs:
networks:
  network: